// src/App.tsx
import { createMemo, For, type Component } from 'solid-js';
import { useRouter } from './lib/contexts/router_context';

const App: Component = () => {
  const { mount } = useRouter();
  const routes = createMemo(() => Object.values(useRouter().routes));

  mount('sign_in');

  return (
    <For each={routes()}>
      {({ Component, props }) => (
        <div class="fixed max-w-screen max-h-screen overflow-visible">
          <Component {...props}></Component>
        </div>
      )}
    </For>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
	import Router from '$lib/router.svelte';
	import { onMount } from 'svelte';

	onMount(() => {
		alt.on('router.mount', Router.mount);
		alt.on('router.unmount', Router.unmount);
		Router.mount('sign_in');
		return () => {
			alt.off('router.mount', Router.mount);
			alt.off('router.unmount', Router.unmount);
		};
	});
</script>

{#each Object.entries(Router.routes) as [route, value] (route)}
	{#await value.lazyComponent then Component}
		<div class="fixed max-w-screen max-h-screen overflow-visible">
			<Component {...value.props} />
		</div>
	{/await}
{/each}
